### ISSUE TITLE
寶可夢巢穴地圖無法新增巢穴點

### ISSUE THREAD

**Issue by Speedman29** [Rplus/PM-nest-map#3]
寶可夢巢穴地圖，要另外在其他地方新增巢穴點，毫無反應。

**Comment by Rplus** [comment]
感謝回報
最近 leafjs 好像有點問題
我找時間看一下 ：）

**Comment by Rplus** [comment]
close by e8dfd1b5bce314788938d9c93ad1272fb9731dd2
