### ISSUE TITLE
再冒昧請求，雖然無關巢穴地圖，可否把全台任務地圖的任務做修正？

### ISSUE THREAD

**Issue by Speedman29** [Rplus/PM-nest-map#4]
現在課題有些已經換新的，有空的話，可否幫忙改正？因為我那地方 他牌雷達還無法完全顯示課題，感謝

**Comment by Rplus** [comment]
這邊走唷~ XD
https://github.com/5upergeo/PMGO-tasks-map/issues

**Comment by HuskyHsu** [comment]
改上去了XDD
不過因為還有line的回報所以只能限制在２０種

**Comment by Speedman29** [comment]
感謝幫忙，不然雷達根本掃不到我們這裡，要自立自強。

**Comment by Speedman29** [comment]
原來LINE回報只能20種課題啊，這是活動又是25種組合，又有原本平日的課題，20個根本不夠放，雖然活動只有短暫的4天XD

**Comment by Speedman29** [comment]
原來LINE回報只能20種課題啊，這次活動又是25種組合，又有原本平日的課題，20個根本不夠放，雖然活動只有短暫的4天XD

**Comment by HuskyHsu** [comment]
等雷達陣亡再來考慮整個大改版ＸＤＤ
主要是messaging-api用的那個格式只能放這樣的量進去，沒想到這次爆炸多惹
